### ISSUE TITLE
LT format not supported

### ISSUE THREAD

**Issue by theodorosidmar** [aldeed/meteor-autoform-bs-datetimepicker#41]
Hello.

As we can see at [https://eonasdan.github.io/bootstrap-datetimepicker/#custom-formats](url), they use "format: 'LT'" when they do not want to show dates. How am I supposed to pick only the time? I'm using LT format but nothing happens.

Thanks.

**Comment by marmeden** [comment]
I am trying to format the date following the "dd/mm/yyyy" pattern in the datePickerOptions but so far it was impossible.  

This autoform packages are great, though.

**Comment by theodorosidmar** [comment]
That just worked fine!

Thank you very much, @ataquino! Appreciate it.
