### ISSUE TITLE
Feature request: Passing dateTimePickerOptions through SimpleSchema

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-autoform-bs-datetimepicker#5]
It would be nice if one could also pass the ```dateTimePickerOptions``` directly through the Schema definition similar to other autoform widgets like:
https://atmospherejs.com/ctjp/autoform-bootstrap-switch

```javascript
{
    date: {
        type: Date,
        autoform: {
            afFieldInput: {
                type: "bootstrap-datetimepicker",
                timezoneId: "America/New_York",
                dateTimePickerOptions: {
                    // Options come here...
                }
            }
        }
    }
}
```

**Comment by aldeed** [comment]
I would think that would work.

**Comment by boustanihani** [comment]
Sorry, you are right, it works :) Maybe also worth mentioning in the docs because the docs currently only mention passing the **dateTimePickerOptions** as a helper function...

**Comment by lucatros** [comment]
This doesn't work for me. I've added the option to ````dateTimePickerOptions: { }```` but it's not accepting any of them. Any tip you would like to share?
Thanks in advance.

**Comment by boustanihani** [comment]
Could you share some code ?

**Comment by lucatros** [comment]
Sure! I'm creating a sample here: http://meteorpad.com/pad/e4cG3nWQCiSqgChPb/AutoForm-DateTimePicker

For some reason the input field is not rendering at all. Trying to figure it out why. I'm sharing in case you can shed some light on this new issue. I'll let you know as soon as I have it working.
Thanks!

**Comment by lucatros** [comment]
Seems I spoke too soon. Apparently, some options work and some don't. For example, I can't set the stepping option nor the language.

**Comment by boustanihani** [comment]
You are using the wrong options.

Use ```minuteStepping``` instead of ```stepping``` and ```language``` instead of ```locale```

**Comment by boustanihani** [comment]
The site http://eonasdan.github.io/bootstrap-datetimepicker/ is now displaying **datetimepicker v4**
but https://atmospherejs.com/tsega/bootstrap3-datetimepicker still uses **datetimepicker v3**

**Comment by lucatros** [comment]
Oh! I see... Thanks! I'll keep that in mind. 
Anyhow, the code on my end looks like the sample I sent and options are still not working, even if I use the v3 options. Any idea how can I troubleshoot it? Sorry for been so bothersome.

**Comment by boustanihani** [comment]
Were you able to find the docs for version 3?

**Comment by boustanihani** [comment]
Which options are not working? I just checked your Meteorpad and ```minuteStepping``` is working as it should...

**Comment by lucatros** [comment]
Nop. I'm just playing with options that work on MeteorPad but not on my code. For example ````calendarWeeks: true,````

**Comment by lucatros** [comment]
On my code, any of the options are working. Even the ones that are working on the MeteorPad sample.

**Comment by boustanihani** [comment]
Is ```calendarWeeks``` a v3-option or a v4-option

**Comment by lucatros** [comment]
Seems ````calendarWeeks ```` it's working on both v3 and v4 since it's working on my sample code and it's on the documentation for v4.

**Comment by boustanihani** [comment]
You mean it is working on Meteorpad but not in your project ?

**Comment by lucatros** [comment]
Exactly. And the code looks the same on both sides. I'm sure there must be a silly mistake somewhere but I can't figure it out.

**Comment by boustanihani** [comment]
I would say compare your package list versions...

**Comment by lucatros** [comment]
Oh my! I told you I was sure it was a silly mistake. In case you are wondering, I was changing the option on the schema for a field but on the browser I was checking other Date field and not the one I was modifying. So silly! I think I need to get some rest and sleep. 
Sorry for the time I made you spend. 

BTW, Do you happen to have link to the v3 docs for datetimepicker?

Thanks!!

**Comment by boustanihani** [comment]
Shit happens ;) I couldn't find the v3 docs, I suggest you open a new issue on https://github.com/Eonasdan/bootstrap-datetimepicker requesting a link for the v3 docs or maybe ask https://github.com/tsega/meteor-bootstrap3-datetimepicker/ to update to version 4...

**Comment by lucatros** [comment]
Will do! Thanks!

**Comment by boustanihani** [comment]
Welcome :+1:

**Comment by comerc** [comment]
You can use V4 now: https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/7

I will make merge branches in the near future.

**Comment by lucatros** [comment]
Hi comerc. I'm playing with it right now.  :)


BTW, in case someone come here looking for version 3 available options, here they are:

````
$.fn.datetimepicker.defaults = {
    pickDate: true,                 //en/disables the date picker
    pickTime: true,                 //en/disables the time picker
    useMinutes: true,               //en/disables the minutes picker
    useSeconds: true,               //en/disables the seconds picker
    useCurrent: true,               //when true, picker will set the value to the current date/time     
    minuteStepping:1,               //set the minute stepping
    minDate:`1/1/1900`,               //set a minimum date
    maxDate: ,     //set a maximum date (defaults to today +100 years)
    showToday: true,                 //shows the today indicator
    language:'en',                  //sets language locale
    defaultDate:"",                 //sets a default date, accepts js dates, strings and moment objects
    disabledDates:[],               //an array of dates that cannot be selected
    enabledDates:[],                //an array of dates that can be selected
    icons = {
        time: 'glyphicon glyphicon-time',
        date: 'glyphicon glyphicon-calendar',
        up:   'glyphicon glyphicon-chevron-up',
        down: 'glyphicon glyphicon-chevron-down'
    }
    useStrict: false,               //use "strict" when validating dates  
    sideBySide: false,              //show the date and time picker side by side
    daysOfWeekDisabled:[]          //for example use daysOfWeekDisabled: [0,6] to disable weekends 
};
````

**Comment by lucatros** [comment]
comerc, sorry for what I'm sure it's a newbie question. I don't have much experience with git.
After running ````git checkout v4beta```` I'm getting: ````error: pathspec 'v4beta' did not match any file(s) known to git.````.
When I run ````git branch -a```` I'm only getting the ````master```` branch. 
Am I missing something?

**Comment by comerc** [comment]
please use instruction:

```
$ meteor add comerc:bs-datetimepicker
$ cd packages
$ git clone https://github.com/comerc/meteor-autoform-bs-datetimepicker.git
$ git checkout v4beta
```

**Comment by lucatros** [comment]
Yeap. That's what I did. I'm getting the error after following those instructions.

**Comment by comerc** [comment]
please use instruction:
```
$ meteor add comerc:bs-datetimepicker
$ cd packages
$ git clone https://github.com/comerc/meteor-autoform-bs-datetimepicker.git
$ cd meteor-autoform-bs-datetimepicker
$ git checkout v4beta
```

add line to ./meteor/packages
```
aldeed:autoform-bs-datetimepicker
```

It works.

**Comment by lucatros** [comment]
it works now :+1: 

Thanks!

**Comment by juliomac** [comment]
Dear Lucatros,

I can't get either language: 'es' nor locale: 'es' to work with your MeteorPad example. I added also the package rzymek:moment-locale-ex and still nothing. Have you solved it?

By the way... which one is V3 or V4?

**Comment by lucatros** [comment]
Did you add ````locale: es```` to the ````dateTimePickerOptions````?

Something like this:

````javascript
	fechaNacimiento: {
		type: Date,
		label: "Fecha de nacimiento",
		autoform: {
			afFieldInput: {
				type: "bootstrap-datetimepicker",
				outMode: 'utcDate',
				dateTimePickerOptions: {
					format: 'L',
					locale: 'es'
				}
			}
		}
	},

````

**Comment by juliomac** [comment]
Yes. That is exactly what I did. But I also tried language and both did not work for me. I am sure I am doing something wrong with the versions of the packages I've installed, but could not figure out what.

I decided to move to another date picker implementation (https://github.com/eternicode/bootstrap-datepicker) and use their i18N solution instead.

```javascript
$.fn.datepicker.dates['es'] = {
    days: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sabado"],
    daysShort: ["Dom","Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
    daysMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
    months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    today: "Hoy",
    clear: "Borrar"
};

**Comment by lucatros** [comment]
On my end, I'm using the v4beta from comerc and it's working with locales.
Check comments above on how to use the version from comerc and you should have no problems with locales.

**Comment by devarashetty** [comment]
when I am using "dateTimePickerOptions" in my schema , my template using that particular field is not rendering .Does any one have idea why it is happening??my schema looks similar like this 
d:
{
    type: String,
    label: "Certification Date",
    optional:true,
    autoform: {
       afFieldInput: {
          type: "bootstrap-datepicker",
          placeholder:"Certification Date Received",
          class:"certification-date-received",
          dateTimePickerOptions: {
            format: 'DD MMMM YYYY '
          }
       }
    }
}

**Comment by Ouro17** [comment]
@devarashetty Try to change type: String to type: Date
@lucratos: Thank you, my locales are working finally!
